<?php
/**
 * Created by PhpStorm.
 * User: mkkn
 * Date: 2015/01/22
 * Time: 0:00
 */

namespace Chatbox\Album\Services\Eloquent;


use Chatbox\Album\Album;
use Illuminate\Database\Eloquent\Model;

class Data extends Model{

    protected $table = "album_data";

    protected $fillable = ["data","created_at"];

    public $timestamps = false;

    public function __construct(array $attributes = array())
    {
        $attributes["created_at"] = \Carbon\Carbon::create();
        parent::__construct($attributes); // TODO: Change the autogenerated stub
    }


}